//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySpecs.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySpecs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemUsers
        ///Account
        ///AccountSID
        ///SecurityDescriptor
        ///SecuritySetting
        ///SecuritySettingAccess
        ///SecuritySettingAuditing
        ///SecuritySettingGroup
        ///SecuritySettingOfLogicalFile
        ///SecuritySettingOfLogicalShare
        ///SecuritySettingOfObject
        ///SecuritySettingOwner
        ///NTEventlogFile
        ///NTLogEvent
        ///NTLogEventComputer
        ///NTLogEventLog
        ///NTLogEventUser.
        /// </summary>
        internal static string Account_Info {
            get {
                return ResourceManager.GetString("Account_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiskDrive
        ///DiskDriveToDiskPartition
        ///DiskPartition
        ///LogicalDisk
        ///LogicalDiskRootDirectory
        ///LogicalDiskToPartition
        ///LogicalFileAccess
        ///LogicalFileAuditing
        ///LogicalFileGroup
        ///LogicalFileOwner
        ///LogicalFileSecuritySetting
        ///TapeDrive.
        /// </summary>
        internal static string Data_Storage {
            get {
                return ResourceManager.GetString("Data_Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMApplication
        ///COMApplicationClasses
        ///COMApplicationSettings
        ///COMClass
        ///ComClassAutoEmulator
        ///ComClassEmulator
        ///COMSetting
        ///ODBCAttribute
        ///ODBCDataSourceAttribute
        ///ODBCDataSourceSpecification
        ///ODBCDriverAttribute
        ///ODBCDriverSoftwareElement
        ///ODBCDriverSpecification
        ///ODBCSourceAttribute
        ///ODBCTranslatorSpecification
        ///Perf
        ///PerfRawData
        ///PerfRawData_ASP_ActiveServerPages
        ///PerfRawData_ASPNET_114322_ASPNETAppsv114322
        ///PerfRawData_ASPNET_114322_ASPNETv114322
        ///PerfRawData_ASPNET_ASPNET
        ///PerfRawData_ASPNET_ASPNETApp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1394Controller
        ///1394ControllerDevice
        ///BaseBoard
        ///Battery
        ///BIOS
        ///Bus
        ///CDROMDrive
        ///CIMLogicalDeviceCIMDataFile
        ///DeviceBus
        ///DeviceMemoryAddress
        ///DeviceSettings
        ///DisplayConfiguration
        ///DisplayControllerConfiguration
        ///DMAChannel
        ///DriverVXD
        ///FloppyController
        ///FloppyDrive
        ///HeatPipe
        ///IDEController
        ///IDEControllerDevice
        ///InfraredDevice
        ///IRQResource
        ///Keyboard
        ///MotherboardDevice
        ///OnBoardDevice
        ///PCMCIAController
        ///PNPAllocatedResource
        ///PnPDevice
        ///PnPEntity
        ///PointingDevice
        ///PortableBattery
        ///PortConnector
        ///PortResource
        ///POT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hardware_Info {
            get {
                return ResourceManager.GetString("Hardware_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CacheMemory
        ///MemoryArray
        ///MemoryArrayLocation
        ///MemoryDevice
        ///MemoryDeviceArray
        ///MemoryDeviceLocation
        ///AssociatedProcessorMemory
        ///DeviceMemoryAddress
        ///LogicalMemoryConfiguration
        ///PerfRawData_PerfOS_Memory
        ///PhysicalMemory
        ///PhysicalMemoryArray
        ///PhysicalMemoryLocation
        ///SMBIOSMemory
        ///SystemLogicalMemoryConfiguration
        ///SystemMemoryResource.
        /// </summary>
        internal static string Memory {
            get {
                return ResourceManager.GetString("Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetworkAdapter
        ///NetworkAdapterConfiguration
        ///NetworkAdapterSetting
        ///NetworkClient
        ///NetworkConnection
        ///NetworkLoginProfile
        ///NetworkProtocol
        ///PerfRawData_Tcpip_ICMP
        ///PerfRawData_Tcpip_IP
        ///PerfRawData_Tcpip_NBTConnection
        ///PerfRawData_Tcpip_NetworkInterface
        ///PerfRawData_Tcpip_TCP
        ///PerfRawData_Tcpip_UDP
        ///PerfRawData_W3SVC_WebService
        ///SystemNetworkConnections.
        /// </summary>
        internal static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACE
        ///ActionCheck
        ///AllocatedResource
        ///ApplicationCommandLine
        ///ApplicationService
        ///ApplicationCommandLine
        ///ApplicationService
        ///Account
        ///AccountSID
        ///ACE
        ///ActionCheck
        ///AllocatedResource
        ///AssociatedBattery
        ///AssociatedProcessorMemory
        ///Process
        ///ProcessStartup
        ///Product
        ///ProductCheck
        ///ProductResource
        ///ProductSoftwareFeatures
        ///ProgIDSpecification
        ///ProgramGroup
        ///ProgramGroupContents
        ///ProgramGroupOrItem
        ///Property
        ///ProtocolBinding
        ///PublishComponentAction
        ///QuickFixEngineering
        ///Refrigeration
        ///Registry
        ///RegistryAction
        ///Sys [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string System_Info {
            get {
                return ResourceManager.GetString("System_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1394Controller
        ///1394ControllerDevice
        ///Account
        ///AccountSID
        ///ACE
        ///ActionCheck
        ///AllocatedResource
        ///ApplicationCommandLine
        ///ApplicationService
        ///AssociatedBattery
        ///AssociatedProcessorMemory
        ///BaseBoard
        ///BaseService
        ///Battery
        ///Binary
        ///BindImageAction
        ///BIOS
        ///BootConfiguration
        ///Bus
        ///CacheMemory
        ///CDROMDrive
        ///CheckCheck
        ///CIMLogicalDeviceCIMDataFile
        ///ClassicCOMApplicationClasses
        ///ClassicCOMClass
        ///ClassicCOMClassSetting
        ///ClassicCOMClassSettings
        ///ClassInfoAction
        ///ClientApplicationSetting
        ///CodecFile
        ///COMApplication
        ///COMApp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Utility {
            get {
                return ResourceManager.GetString("Utility", resourceCulture);
            }
        }
    }
}
